# Generated by Django 2.0.1 on 2018-02-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(choices=[('Colombia', 'CO'), ('Estados Unidos', 'USA'), ('Mexico', 'MX')], max_length=3),
        ),
    ]
